# -*- coding: utf-8 -*-
"""Copy_of_refocus_modified.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-yvpTNGztR0KfOEtpdkpBg3aUzuiGsH
"""

!pip install transformers==4.46.1

!pip install flash-attn --no-build-isolation
# !pip install --upgrade transformers

from PIL import Image
import requests
from transformers import AutoModelForCausalLM
from transformers import AutoProcessor
from PIL import Image
import requests
from transformers import AutoModelForCausalLM
from transformers import AutoProcessor

# model_id = "microsoft/Phi-3.5-vision-instruct"
model_id = "Fiaa/ReFocus"
subfolder = "lr1e-06_ep2_bb1_edit0_aug0"
# Note: set _attn_implementation='eager' if you don't have flash_attn installed
model_refocus = AutoModelForCausalLM.from_pretrained(
  model_id,
   subfolder=subfolder,
  device_map="cuda",
  trust_remote_code=True,
  torch_dtype="auto",
  # _attn_implementation='flash_attention_2'
)

# for best performance, use num_crops=4 for multi-frame, num_crops=16 for single-frame.
processor_refocus = AutoProcessor.from_pretrained(model_id,  subfolder=subfolder,
  trust_remote_code=True,
  num_crops=4
)

model_id = "microsoft/Phi-3-vision-128k-instruct"
model_phi3v = AutoModelForCausalLM.from_pretrained(model_id, device_map="cuda", trust_remote_code=True, torch_dtype="auto", _attn_implementation='eager') # use _attn_implementation='eager' to disable flash attention
processor_phi3v = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)



# # 1. Create images and placeholder
# images = []
# placeholder = ""

# for i in range(1, 3):
#     url = f"https://image.slidesharecdn.com/azureintroduction-191206101932/75/Introduction-to-Microsoft-Azure-Cloud-{i}-2048.jpg"
#     images.append(Image.open(requests.get(url, stream=True).raw))
#     placeholder += f"<|image_{i}|>\n"

# # 2. Create message
# messages = [
#     {"role": "user", "content": placeholder + "Summarize the deck of slides."},
# ]

# # 3. Create prompt (text only)
# prompt = processor.tokenizer.apply_chat_template(
#     messages,
#     tokenize=False,
#     add_generation_prompt=True,
# )

# # 4. Process (prompt + images) to inputs
# inputs = processor(prompt, images=images, return_tensors="pt").to(model.device)

# # 5. Generate
# generation_args = {
#     "max_new_tokens": 1000,
#     "temperature": 0.0,
#     "do_sample": False,
# }
# generate_ids = model.generate(
#     **inputs,
#     eos_token_id=processor.tokenizer.eos_token_id,
#     **generation_args
# )

# # 6. Remove prompt part
# generate_ids = generate_ids[:, inputs['input_ids'].shape[1]:]

# # 7. Decode
# response = processor.batch_decode(
#     generate_ids,
#     skip_special_tokens=True,
#     clean_up_tokenization_spaces=False
# )[0]

# print(response)

# raw_url = "https://github.com/vis-nlp/ChartQA/raw/main/ChartQA%20Dataset/test/png/multi_col_60912.png"
# resp = requests.get(raw_url, stream=True)
# images = Image.open(resp.raw)

# # 2. Create message
# messages = [
#     {"role": "user", "content": "<|image_1|>\nWhat was the female population of Tunisia in 2019?"},
# ]

# # 3. Create prompt (text only)
# prompt = processor.tokenizer.apply_chat_template(
#     messages,
#     tokenize=False,
#     add_generation_prompt=True,
# )

# # 4. Process (prompt + images) to inputs
# inputs = processor(prompt, images=images, return_tensors="pt").to(model.device)

# # 5. Generate
# generation_args = {
#     "max_new_tokens": 1000,
#     "temperature": 0.0,
#     "do_sample": False,
# }
# generate_ids = model.generate(
#     **inputs,
#     eos_token_id=processor.tokenizer.eos_token_id,
#     **generation_args
# )

# # 6. Remove prompt part
# generate_ids = generate_ids[:, inputs['input_ids'].shape[1]:]

# # 7. Decode
# response = processor.batch_decode(
#     generate_ids,
#     skip_special_tokens=True,
#     clean_up_tokenization_spaces=False
# )[0]

# print(response)

from PIL import Image
import requests
from transformers import AutoModelForCausalLM
from transformers import AutoProcessor
from PIL import Image
import requests
from transformers import AutoModelForCausalLM
from transformers import AutoProcessor

# model_id = "microsoft/Phi-3.5-vision-instruct"
model_id = "Fiaa/ReFocus"
subfolder = "lr1e-06_ep2_bb1_edit0_aug0"
# Note: set _attn_implementation='eager' if you don't have flash_attn installed
model_refocus = AutoModelForCausalLM.from_pretrained(
  model_id,
   subfolder=subfolder,
  device_map="cuda",
  trust_remote_code=True,
  torch_dtype="auto",
  # _attn_implementation='flash_attention_2'
)

# for best performance, use num_crops=4 for multi-frame, num_crops=16 for single-frame.
processor_refocus = AutoProcessor.from_pretrained(model_id,  subfolder=subfolder,
  trust_remote_code=True,
  num_crops=4
)

model_id = "microsoft/Phi-3-vision-128k-instruct"
model_phi3v = AutoModelForCausalLM.from_pretrained(model_id, device_map="cuda", trust_remote_code=True, torch_dtype="auto", _attn_implementation='eager') # use _attn_implementation='eager' to disable flash attention
processor_phi3v = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

from PIL import Image
import requests
from transformers import AutoModelForCausalLM, AutoProcessor
import re
import ast
from typing import List, Dict

def refocus(model, processor, image: Image.Image, question: str, max_new_tokens: int = 1000) -> str:
    """
    Asks a question about an image using the Phi-3 Vision model.

    Args:
        model: The Phi-3 Vision model (loaded with `AutoModelForCausalLM`).
        processor: The corresponding processor (loaded with `AutoProcessor`).
        image (PIL.Image.Image): Input image.
        question (str): The question to ask about the image.
        max_new_tokens (int): Max tokens to generate in response.

    Returns:
        str: The model's answer.
    """
    # Create message
    messages = [
        {"role": "user", "content": f"<|image_1|>\n{question}"}
    ]

    # Create prompt
    prompt = processor.tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    # Process input
    inputs = processor(prompt, images=image, return_tensors="pt").to(model.device)

    # Generate
    generate_ids = model.generate(
        **inputs,
        eos_token_id=processor.tokenizer.eos_token_id,
        max_new_tokens=max_new_tokens,
        temperature=0.0,
        do_sample=False
    )

    # Remove prompt tokens
    generate_ids = generate_ids[:, inputs['input_ids'].shape[1]:]

    # Decode
    response = processor.batch_decode(
        generate_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False
    )[0]

    return response

def extract_bounding_boxes(model_output: str) -> List[Dict[str, int]]:
    """
    Extracts a list of bounding box dictionaries from model output text.

    Args:
        model_output (str): The output string from the model.

    Returns:
        List[Dict[str, int]]: A list of bounding box dictionaries with keys 'x1', 'y1', 'x2', 'y2'.
    """
    # Match the full list of bounding boxes
    match = re.search(r"\[\s*{[^]]+}\s*\]", model_output)
    if match:
        try:
            bboxes = ast.literal_eval(match.group(0))
            if isinstance(bboxes, list) and all(isinstance(b, dict) for b in bboxes):
                return bboxes
        except (SyntaxError, ValueError):
            pass
    return []

output = "The areas to focus on in the image have bounding box coordinates: [{'x1': 655, 'y1': 45, 'x2': 725, 'y2': 400}, {'x1': 100, 'y1': 80, 'x2': 150, 'y2': 130}]."
print(extract_bounding_boxes(output))

def crop_image(image: Image.Image, bbox: dict, zoom_factor: int = 5) -> Image.Image:
    """
    Crops a region from the image using bbox and zooms into it.

    Args:
        image (PIL.Image.Image): Input image.
        bbox (dict): A dictionary with keys 'x1', 'y1', 'x2', 'y2' for cropping.
        zoom_factor (int): Factor to zoom the cropped region.

    Returns:
        PIL.Image.Image: The zoomed-in cropped region.
    """
    # Crop the region
    cropped_region = image.crop((bbox['x1'], bbox['y1'], bbox['x2'], bbox['y2']))

    # Resize (zoom) the cropped region
    zoomed_image = cropped_region.resize(
        (cropped_region.width * zoom_factor, cropped_region.height * zoom_factor),
        Image.LANCZOS  # High-quality resampling
    )

    return zoomed_image

from PIL import Image, ImageDraw

def draw_bboxes_on_image(image: Image.Image, bboxes: list) -> Image.Image:
    """
    Draws all bounding boxes on the image.

    Args:
        image (PIL.Image.Image): The image on which to draw the bounding boxes.
        bboxes (list): A list of dictionaries, where each dictionary contains
                       the bounding box coordinates ('x1', 'y1', 'x2', 'y2').

    Returns:
        PIL.Image.Image: The image with bounding boxes drawn.
    """
    # Create a drawing context
    draw = ImageDraw.Draw(image)

    # Draw each bounding box
    for bbox in bboxes:
        draw.rectangle(
            [(bbox['x1'], bbox['y1']), (bbox['x2'], bbox['y2'])],
            outline="red", width=3
        )

    return image

# # Example usage
# image = Image.open("input_image.png")  # Replace with your image
# bboxes = [
#     {'x1': 637, 'y1': 45, 'x2': 725, 'y2': 400},
#     # Add more bounding boxes here if needed
# ]

# # Draw bounding boxes on the image
# output_image = draw_bboxes_on_image(image, bboxes)

# # Save or show the output image
# # output_image.save("output_with_bboxes.png")
# # or output_image.show() to display the image

from PIL import Image
from transformers import AutoModelForCausalLM, AutoProcessor

def phi3v(model, processor, image1: Image.Image, image2: Image.Image, question: str, device: str = "cuda:0", max_new_tokens: int = 500) -> str:
    """
    Run inference on two images and a question using Phi-3 Vision.

    Args:
        model: Phi-3 Vision model (already loaded).
        processor: Corresponding processor (already loaded).
        image1 (PIL.Image.Image): The first image (with bounding box).
        image2 (PIL.Image.Image): The second image (zoomed-in version).
        question (str): The question to ask about the images.
        device (str): Device to run the model on ("cuda:0", "cpu", etc.).
        max_new_tokens (int): Maximum number of new tokens to generate.

    Returns:
        str: Model's textual response.
    """
    # Format the message with two images
    messages = [
        {"role": "user", "content": f"<|image_1|> \n<|image_2|> \nimage_1 is the image with bounding box drawn for the most important region and image_2 is the zoomed-in version of image_1.\n{question}"}
    ]

    # Create prompt from messages
    prompt = processor.tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    # Prepare model inputs for both images
    inputs = processor(prompt, [image1, image2], return_tensors="pt").to(device)

    # Generate response
    generate_ids = model.generate(
        **inputs,
        eos_token_id=processor.tokenizer.eos_token_id,
        max_new_tokens=max_new_tokens,
        temperature=0.0,
        do_sample=False
    )

    # Remove prompt from output
    generate_ids = generate_ids[:, inputs['input_ids'].shape[1]:]

    # Decode the generated response
    response = processor.batch_decode(
        generate_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False
    )[0]

    return response

def get_largest_bbox(bboxes):
    return max(bboxes, key=lambda b: (b['x2'] - b['x1']) * (b['y2'] - b['y1']))

def calc_output(question,image):
  bboxes=refocus(model_refocus,processor_refocus,image,question)
  bboxes=extract_bounding_boxes(bboxes)
  imgbbox=draw_bboxes_on_image(image,bboxes)
  bbox = get_largest_bbox(bboxes)
  zoomimg = crop_image(image, bbox)
  result=phi3v(model_phi3v,processor_phi3v,imgbbox,zoomimg,question)
  print(result)
  return result

import pandas as pd

def compute_accuracy(data_path):
    df=pd.read_json(data_path)
    #rows=len(df)
    total =500
    correct=0
    for idx, row in df.iterrows():
        imgname = row['imgname']
        question = row['query']
        label = row['label']
        image_url = f'../../ChartQADataset/test/png/{imgname}'
        resp = requests.get(image_url, stream=True)
        image = Image.open(resp.raw)
        model_answer = calc_output(image, question)
        model_answer=  model_answer.replace('%','').replace('$','').replace(',','' )
        #model_answer=clean_string(model_answer)
        if model_answer.endswith('.0'):
            model_answer = model_answer[:-2]  # Remove '.0'
        elif model_answer.endswith('.'):
            model_answer = model_answer[:-1]  # Remove trailing '.'

        print(f'{idx}, model_answer: {model_answer}, actual_answer: {label}',end=' ')
        if model_answer == label:
            correct += 1
        print(f'correct cnt: {correct}')
    print(f'accuracy: {correct}')